# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproposal',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
    ]
