# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20171117_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproposal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Final'), (3, 'Accepted'), (4, 'Rejected'), (6, 'Withdrawn')], default=1),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Final'), (3, 'Accepted'), (4, 'Rejected'), (6, 'Withdrawn')], default=1),
        ),
    ]
