# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20171121_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16),
        ),
    ]
