# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20171121_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvote',
            name='vote',
            field=models.CharField(blank=True, choices=[('plus_one', '+1: Yes, I agree'), ('plus_zero', "+0: I don't feel strongly about it, but I'm okay with this."), ('minus_zero', "-0: I won't get in the way, but I'd rather we didn't do this."), ('minus_one', '-1: I object on the following grounds')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(blank=True, choices=[('plus_one', '+1: Yes, I agree'), ('plus_zero', "+0: I don't feel strongly about it, but I'm okay with this."), ('minus_zero', "-0: I won't get in the way, but I'd rather we didn't do this."), ('minus_one', '-1: I object on the following grounds')], max_length=16, null=True),
        ),
    ]
