# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20171121_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvote',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
