# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20171122_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
